CREATE OR ALTER FUNCTION dbo.vf_IsDate
(
    @value NVARCHAR(MAX),
    @param NVARCHAR(MAX)
)
RETURNS BIT
AS
BEGIN
    IF @value IS NULL RETURN 1; DECLARE @style INT=CASE UPPER(ISNULL(@param,'YYYY-MM-DD')) WHEN 'YYYY-MM-DD' THEN 23 WHEN 'DD-MM-YYYY' THEN 105 WHEN 'MM/DD/YYYY' THEN 101 WHEN 'YYYY/MM/DD' THEN 111 ELSE 23 END; RETURN IIF(TRY_CONVERT(DATE,@value,@style) IS NOT NULL,1,0);
END
